"""sync schema to models: roles, mfa, billing, imap, domain lifecycle

Revision ID: 391f199da8a5
Revises: a1b2c3d4e5f6
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '391f199da8a5'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_tokens',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('hashed', sa.String(length=64), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_tokens'))
    )
    op.create_index(op.f('ix_export_tokens_prefix'), 'export_tokens', ['prefix'], unique=False)
    op.create_index(op.f('ix_export_tokens_tenant_id'), 'export_tokens', ['tenant_id'], unique=False)
    op.create_table('graph_verdicts',
    sa.Column('registrable_domain', sa.String(length=253), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('first_reported', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reported', sa.DateTime(timezone=True), nullable=False),
    sa.Column('techniques', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('reporter_tenant_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('registrable_domain', name=op.f('pk_graph_verdicts'))
    )
    op.create_table('llm_usage',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('mailbox_id', sa.Uuid(), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('cost_micros', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage')),
    sa.UniqueConstraint('mailbox_id', 'period', name=op.f('uq_llm_usage_mailbox_id'))
    )
    op.create_index(op.f('ix_llm_usage_mailbox_id'), 'llm_usage', ['mailbox_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_tenant_id'), 'llm_usage', ['tenant_id'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('events', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_endpoints'))
    )
    op.create_index(op.f('ix_webhook_endpoints_tenant_id'), 'webhook_endpoints', ['tenant_id'], unique=False)
    # NOTE (hand-adjusted from autogenerate): every NOT NULL column added to an
    # EXISTING, possibly-populated table carries a server_default so it applies
    # cleanly to existing rows — exactly matching the runtime self-heal in
    # envelock/db.py (_RUNTIME_COLUMNS). The ORM still supplies values on write;
    # the server_default only backfills rows that predate the column.
    op.add_column('alerts', sa.Column('counterparty_domain', sa.String(length=253), nullable=True))
    op.create_index(op.f('ix_alerts_counterparty_domain'), 'alerts', ['counterparty_domain'], unique=False)
    op.add_column('domains', sa.Column('verification_method', sa.String(length=8), nullable=False, server_default='txt'))
    op.add_column('mailbox_credentials', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=16), nullable=False, server_default='member'))
    op.add_column('users', sa.Column('status', sa.String(length=16), nullable=False, server_default='active'))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('recovery_hashes', postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('phone_otp_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('phone_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_otp_expires_at')
    op.drop_column('users', 'phone_otp_hash')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'recovery_hashes')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    op.drop_column('mailbox_credentials', 'token_expires_at')
    op.drop_column('domains', 'verification_method')
    op.drop_index(op.f('ix_alerts_counterparty_domain'), table_name='alerts')
    op.drop_column('alerts', 'counterparty_domain')
    op.drop_index(op.f('ix_webhook_endpoints_tenant_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_llm_usage_tenant_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_mailbox_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_table('graph_verdicts')
    op.drop_index(op.f('ix_export_tokens_tenant_id'), table_name='export_tokens')
    op.drop_index(op.f('ix_export_tokens_prefix'), table_name='export_tokens')
    op.drop_table('export_tokens')
    # ### end Alembic commands ###
