"""initial schema

Revision ID: 9f9ed2127394
Revises: 
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import envelock.types


revision: str = '9f9ed2127394'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('detail', envelock.types.JsonDict(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('domain_trial_ledger',
    sa.Column('registrable_domain', sa.String(length=253), nullable=False),
    sa.Column('first_trial_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_tenant_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('payment_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('override_by', sa.Uuid(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('registrable_domain', name=op.f('pk_domain_trial_ledger'))
    )
    op.create_index(op.f('ix_domain_trial_ledger_payment_fingerprint'), 'domain_trial_ledger', ['payment_fingerprint'], unique=False)
    op.create_table('invoices',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('platform_cents', sa.Integer(), nullable=False),
    sa.Column('protected_cents', sa.Integer(), nullable=False),
    sa.Column('monitored_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('breakdown', envelock.types.JsonDict(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscriptions')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_push_subscriptions_endpoint'))
    )
    op.create_index(op.f('ix_push_subscriptions_tenant_id'), 'push_subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('billing_term', sa.String(length=16), nullable=False),
    sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method_ok', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_table('usage_meters',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('messages_analysed', sa.Integer(), nullable=False),
    sa.Column('attachments_seen', sa.Integer(), nullable=False),
    sa.Column('attachments_cache_hit', sa.Integer(), nullable=False),
    sa.Column('attachments_static_resolved', sa.Integer(), nullable=False),
    sa.Column('attachments_detonated', sa.Integer(), nullable=False),
    sa.Column('url_lookups_free', sa.Integer(), nullable=False),
    sa.Column('url_lookups_paid', sa.Integer(), nullable=False),
    sa.Column('sms_sent', sa.Integer(), nullable=False),
    sa.Column('external_cost_micros', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_meters')),
    sa.UniqueConstraint('tenant_id', 'day', name=op.f('uq_usage_meters_tenant_id'))
    )
    op.create_index(op.f('ix_usage_meters_day'), 'usage_meters', ['day'], unique=False)
    op.create_index(op.f('ix_usage_meters_tenant_id'), 'usage_meters', ['tenant_id'], unique=False)
    op.create_table('counterparties',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('registrable_domain', sa.String(length=253), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('verified_phone', sa.String(length=32), nullable=True),
    sa.Column('median_reply_seconds', sa.Integer(), nullable=True),
    sa.Column('known_dkim_domains', envelock.types.StringList(), nullable=False),
    sa.Column('known_mail_clients', envelock.types.StringList(), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_counterparties_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparties')),
    sa.UniqueConstraint('tenant_id', 'registrable_domain', name=op.f('uq_counterparties_tenant_id'))
    )
    op.create_index(op.f('ix_counterparties_registrable_domain'), 'counterparties', ['registrable_domain'], unique=False)
    op.create_index(op.f('ix_counterparties_tenant_id'), 'counterparties', ['tenant_id'], unique=False)
    op.create_table('domains',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=253), nullable=False),
    sa.Column('registrable_domain', sa.String(length=253), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('is_defensive', sa.Boolean(), nullable=False),
    sa.Column('integration_tier', sa.Integer(), nullable=True),
    sa.Column('mx_hosts', envelock.types.StringList(), nullable=True),
    sa.Column('dmarc_policy', sa.String(length=16), nullable=True),
    sa.Column('spf_record', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_domains_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domains')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_domains_tenant_id'))
    )
    op.create_index(op.f('ix_domains_registrable_domain'), 'domains', ['registrable_domain'], unique=False)
    op.create_index(op.f('ix_domains_tenant_id'), 'domains', ['tenant_id'], unique=False)
    op.create_table('lookalike_domains',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('protected_domain', sa.String(length=253), nullable=False),
    sa.Column('candidate_domain', sa.String(length=253), nullable=False),
    sa.Column('technique', sa.String(length=32), nullable=False),
    sa.Column('similarity', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_mx', sa.Boolean(), nullable=False),
    sa.Column('has_web', sa.Boolean(), nullable=False),
    sa.Column('first_seen_source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_lookalike_domains_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lookalike_domains')),
    sa.UniqueConstraint('tenant_id', 'candidate_domain', name=op.f('uq_lookalike_domains_tenant_id'))
    )
    op.create_index(op.f('ix_lookalike_domains_candidate_domain'), 'lookalike_domains', ['candidate_domain'], unique=False)
    op.create_index(op.f('ix_lookalike_domains_protected_domain'), 'lookalike_domains', ['protected_domain'], unique=False)
    op.create_index(op.f('ix_lookalike_domains_tenant_id'), 'lookalike_domains', ['tenant_id'], unique=False)
    op.create_table('sender_profiles',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('features', envelock.types.JsonDict(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sender_profiles_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sender_profiles')),
    sa.UniqueConstraint('tenant_id', 'address', name=op.f('uq_sender_profiles_tenant_id'))
    )
    op.create_index(op.f('ix_sender_profiles_address'), 'sender_profiles', ['address'], unique=False)
    op.create_index(op.f('ix_sender_profiles_tenant_id'), 'sender_profiles', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('out_of_band_email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('bank_records',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('scheme', sa.String(length=16), nullable=False),
    sa.Column('identifier', sa.String(length=128), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], name=op.f('fk_bank_records_counterparty_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_bank_records_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_records')),
    sa.UniqueConstraint('counterparty_id', 'scheme', 'identifier', name=op.f('uq_bank_records_counterparty_id'))
    )
    op.create_index(op.f('ix_bank_records_counterparty_id'), 'bank_records', ['counterparty_id'], unique=False)
    op.create_index('ix_bank_records_lookup', 'bank_records', ['tenant_id', 'counterparty_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_bank_records_tenant_id'), 'bank_records', ['tenant_id'], unique=False)
    op.create_table('mailboxes',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=True),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('mailbox_class', sa.String(length=16), nullable=False),
    sa.Column('integration_tier', sa.Integer(), nullable=False),
    sa.Column('sources', envelock.types.StringList(), nullable=False),
    sa.Column('protection_level', sa.String(length=16), nullable=False),
    sa.Column('inactive_detections', envelock.types.StringList(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('known_user_count', sa.Integer(), nullable=False),
    sa.Column('backfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_mailboxes_domain_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_mailboxes_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mailboxes')),
    sa.UniqueConstraint('tenant_id', 'address', name=op.f('uq_mailboxes_tenant_id'))
    )
    op.create_index(op.f('ix_mailboxes_address'), 'mailboxes', ['address'], unique=False)
    op.create_index(op.f('ix_mailboxes_tenant_id'), 'mailboxes', ['tenant_id'], unique=False)
    op.create_table('alerts',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('mailbox_id', sa.Uuid(), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('requires_callback', sa.Boolean(), nullable=False),
    sa.Column('callback_phone', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], name=op.f('fk_alerts_mailbox_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_alerts_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_mailbox_id'), 'alerts', ['mailbox_id'], unique=False)
    op.create_index('ix_alerts_open', 'alerts', ['tenant_id', 'state', 'tier'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_alerts_tier'), 'alerts', ['tier'], unique=False)
    op.create_table('mailbox_credentials',
    sa.Column('mailbox_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('imap_host', sa.String(length=253), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=False),
    sa.Column('key_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], name=op.f('fk_mailbox_credentials_mailbox_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mailbox_credentials')),
    sa.UniqueConstraint('mailbox_id', name=op.f('uq_mailbox_credentials_mailbox_id'))
    )
    op.create_index(op.f('ix_mailbox_credentials_tenant_id'), 'mailbox_credentials', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('mailbox_id', sa.Uuid(), nullable=False),
    sa.Column('rfc_message_id', sa.String(length=998), nullable=True),
    sa.Column('thread_key', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('sender_address', sa.String(length=320), nullable=False),
    sa.Column('sender_display', sa.String(length=255), nullable=True),
    sa.Column('reply_to_address', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('remediable', sa.Boolean(), nullable=False),
    sa.Column('spf', sa.String(length=16), nullable=True),
    sa.Column('dkim', sa.String(length=16), nullable=True),
    sa.Column('dmarc', sa.String(length=16), nullable=True),
    sa.Column('attachment_hashes', envelock.types.StringList(), nullable=False),
    sa.Column('body_storage_key', sa.String(length=512), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('quarantined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], name=op.f('fk_messages_mailbox_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_messages_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_mailbox_id'), 'messages', ['mailbox_id'], unique=False)
    op.create_index(op.f('ix_messages_rfc_message_id'), 'messages', ['rfc_message_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_address'), 'messages', ['sender_address'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_messages_thread_key'), 'messages', ['thread_key'], unique=False)
    op.create_table('sensor_sessions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('mailbox_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('asn', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('is_vpn', sa.Boolean(), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('mail_client', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], name=op.f('fk_sensor_sessions_mailbox_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_sessions'))
    )
    op.create_index(op.f('ix_sensor_sessions_device_fingerprint'), 'sensor_sessions', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_sensor_sessions_last_seen_at'), 'sensor_sessions', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_sensor_sessions_mailbox_id'), 'sensor_sessions', ['mailbox_id'], unique=False)
    op.create_index(op.f('ix_sensor_sessions_tenant_id'), 'sensor_sessions', ['tenant_id'], unique=False)
    op.create_table('findings',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('mailbox_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('service', sa.String(length=8), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence', envelock.types.JsonDict(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_findings_alert_id')),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], name=op.f('fk_findings_mailbox_id')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_findings_message_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_findings_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index(op.f('ix_findings_alert_id'), 'findings', ['alert_id'], unique=False)
    op.create_index(op.f('ix_findings_service'), 'findings', ['service'], unique=False)
    op.create_index(op.f('ix_findings_tenant_id'), 'findings', ['tenant_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('rung', sa.String(length=4), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cost_micros', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_notification_deliveries_alert_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries'))
    )
    op.create_index(op.f('ix_notification_deliveries_alert_id'), 'notification_deliveries', ['alert_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_tenant_id'), 'notification_deliveries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_deliveries_tenant_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_alert_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_findings_tenant_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_service'), table_name='findings')
    op.drop_index(op.f('ix_findings_alert_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_sensor_sessions_tenant_id'), table_name='sensor_sessions')
    op.drop_index(op.f('ix_sensor_sessions_mailbox_id'), table_name='sensor_sessions')
    op.drop_index(op.f('ix_sensor_sessions_last_seen_at'), table_name='sensor_sessions')
    op.drop_index(op.f('ix_sensor_sessions_device_fingerprint'), table_name='sensor_sessions')
    op.drop_table('sensor_sessions')
    op.drop_index(op.f('ix_messages_thread_key'), table_name='messages')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_address'), table_name='messages')
    op.drop_index(op.f('ix_messages_rfc_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_mailbox_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_mailbox_credentials_tenant_id'), table_name='mailbox_credentials')
    op.drop_table('mailbox_credentials')
    op.drop_index(op.f('ix_alerts_tier'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index('ix_alerts_open', table_name='alerts')
    op.drop_index(op.f('ix_alerts_mailbox_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_mailboxes_tenant_id'), table_name='mailboxes')
    op.drop_index(op.f('ix_mailboxes_address'), table_name='mailboxes')
    op.drop_table('mailboxes')
    op.drop_index(op.f('ix_bank_records_tenant_id'), table_name='bank_records')
    op.drop_index('ix_bank_records_lookup', table_name='bank_records')
    op.drop_index(op.f('ix_bank_records_counterparty_id'), table_name='bank_records')
    op.drop_table('bank_records')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sender_profiles_tenant_id'), table_name='sender_profiles')
    op.drop_index(op.f('ix_sender_profiles_address'), table_name='sender_profiles')
    op.drop_table('sender_profiles')
    op.drop_index(op.f('ix_lookalike_domains_tenant_id'), table_name='lookalike_domains')
    op.drop_index(op.f('ix_lookalike_domains_protected_domain'), table_name='lookalike_domains')
    op.drop_index(op.f('ix_lookalike_domains_candidate_domain'), table_name='lookalike_domains')
    op.drop_table('lookalike_domains')
    op.drop_index(op.f('ix_domains_tenant_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_registrable_domain'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_counterparties_tenant_id'), table_name='counterparties')
    op.drop_index(op.f('ix_counterparties_registrable_domain'), table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_index(op.f('ix_usage_meters_tenant_id'), table_name='usage_meters')
    op.drop_index(op.f('ix_usage_meters_day'), table_name='usage_meters')
    op.drop_table('usage_meters')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_tenant_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_domain_trial_ledger_payment_fingerprint'), table_name='domain_trial_ledger')
    op.drop_table('domain_trial_ledger')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
